#ifndef BADKING_COMPAT_H
#define BADKING_COMPAT_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <stdarg.h>

/* Ghidra auto-generated types */
typedef unsigned char undefined1;
typedef unsigned short undefined2;
typedef unsigned int undefined4;
typedef unsigned char byte;
typedef unsigned short word;
typedef unsigned int dword;
typedef int bool;
#define true 1
#define false 0

/* Remove 16-bit calling conventions */
#define __cdecl16far
#define __cdecl16near
#define __cdecl16

/* Stub out Windows 3.x API calls */
#define INITTASK() 1
#define INITAPP(x,y) 1
#define WAITEVENT(x,y)
#define LOCKSEGMENT(x,y)
#define UNLOCKSEGMENT()
#define GETWINFLAGS(x) 0
#define LOCALALLOC(x,y) NULL
#define LOCALFREE(x)
#define LOCALREALLOC(x,y,z) NULL
#define BEGINPAINT(x,y) NULL
#define ENDPAINT(x,y)
#define CREATECARET(x,y,z,w)
#define DESTROYCARET()
#define CREATEWINDOW(a,b,c,d,e,f,g,h,i,j,k) NULL
#define DEFWINDOWPROC(a,b,c,d) 0
#define DESTROYWINDOW(x) 0
#define DISPATCHMESSAGE(x) 0
#define ENABLEMENUITEM(a,b,c)
#define GETDC(x) NULL
#define GETDESKTOPWINDOW() NULL
#define GETKEYSTATE(x) 0
#define GETMESSAGE(a,b,c,d) 0
#define GETMODULEFILENAME(a,b,c) 0
#define GETSTOCKOBJECT(x) NULL
#define GETSYSTEMMENU(x,y) NULL
#define GETSYSTEMMETRICS(...) 0
#define GETTEXTMETRICS(x,y) 0
#define INVALIDATERECT(a,b,c)
#define LOADCURSOR(x,y) NULL
#define LOADICON(x,y) NULL
#define LOADLIBRARY(x) NULL
#define MESSAGEBEEP(x)
#define MESSAGEBOX(a,b,c,d) 0
#define PEEKMESSAGE(a,b,c,d,e) 0
#define POSTQUITMESSAGE(x)
#define REGISTERCLASS(x) 0
#define RELEASEDC(a,b)
#define SCROLLWINDOW(a,b,c,d,e)
#define SELECTOBJECT(a,b) NULL
#define SETCARETPOS(x,y)
#define SETSCROLLPOS(a,b,c) 0
#define SETSCROLLRANGE(a,b,c,d,e)
#define SETWINDOWTEXT(a,b)
#define SHOWCARET(x)
#define SHOWWINDOW(x,y) 0
#define TRANSLATEMESSAGE(x) 0
#define UPDATEWINDOW(x)
#define TEXTOUT(a,b,c,d,e)
#define OEMTOANSI(a,b,c)
#define _WSPRINTF sprintf

/* Console I/O stubs */
#define _getch getchar
#define _getche getchar
#define _kbhit() 1
#define _putch putchar

/* Window/GUI stubs */
#define __InitEasyWin()
#define __DoneEasyWin()
#define __ExitEasyWin()
#define __CreateEasyWin() NULL
#define __errorBox(x,y)
#define __errorExitBox(x,y)

/* Windows types */
typedef void* HWND;
typedef void* HDC;
typedef void* HINSTANCE;
typedef void* HMODULE;
typedef void* HMENU;
typedef void* HICON;
typedef void* HCURSOR;
typedef void* HBRUSH;
typedef void* HFONT;
typedef void* HBITMAP;
typedef unsigned int UINT;
typedef unsigned long DWORD;
typedef long LONG;
typedef int BOOL;
typedef char* LPSTR;
typedef const char* LPCSTR;
typedef void* LPVOID;
typedef void* FARPROC;

/* MSG structure stub */
typedef struct {
    HWND hwnd;
    UINT message;
    int wParam;
    long lParam;
    DWORD time;
} MSG;

/* PAINTSTRUCT stub */
typedef struct {
    HDC hdc;
    int fErase;
} PAINTSTRUCT;

/* RECT stub */
typedef struct {
    int left;
    int top;
    int right;
    int bottom;
} RECT;

/* TEXTMETRIC stub */
typedef struct {
    int tmHeight;
    int tmAscent;
    int tmDescent;
    int tmInternalLeading;
    int tmExternalLeading;
    int tmAveCharWidth;
    int tmMaxCharWidth;
    int tmWeight;
    int tmOverhang;
    int tmDigitizedAspectX;
    int tmDigitizedAspectY;
    char tmFirstChar;
    char tmLastChar;
    char tmDefaultChar;
    char tmBreakChar;
    char tmItalic;
    char tmUnderlined;
    char tmStruckOut;
    char tmPitchAndFamily;
    char tmCharSet;
} TEXTMETRIC;

/* WNDCLASS stub */
typedef struct {
    UINT style;
    void* lpfnWndProc;
    int cbClsExtra;
    int cbWndExtra;
    HINSTANCE hInstance;
    HICON hIcon;
    HCURSOR hCursor;
    HBRUSH hbrBackground;
    LPCSTR lpszMenuName;
    LPCSTR lpszClassName;
} WNDCLASS;

/* Point stub */
typedef struct {
    int x;
    int y;
} POINT;

/* GetProcAddress stub */
#define GetProcAddress(x,y) NULL

/* MAKEPOINT stub */
#define MAKEPOINT(x) ((POINT){0,0})

/* LOWORD/HIWORD stubs */
#define LOWORD(x) ((unsigned short)(x))
#define HIWORD(x) ((unsigned short)(((unsigned int)(x)) >> 16))

/* VK_ key constants */
#define VK_RETURN 0x0D
#define VK_ESCAPE 0x1B
#define VK_SPACE 0x20

/* Message constants */
#define WM_CREATE 0x0001
#define WM_PAINT 0x000F
#define WM_DESTROY 0x0002
#define WM_KEYDOWN 0x0100
#define WM_CHAR 0x0102
#define WM_LBUTTONDOWN 0x0201
#define WM_COMMAND 0x0111
#define WM_CLOSE 0x0010

/* Window style constants */
#define WS_OVERLAPPEDWINDOW 0x00CF0000
#define CW_USEDEFAULT 0x80000000

/* swi stub - just return 0 */
#define swi(x) 0

/* code type stub */
typedef int (*code)();

/* Ghidra helper macros - these are auto-generated by Ghidra */
#define CONCAT11(a,b) ((unsigned short)(((unsigned char)(a)) << 8 | ((unsigned char)(b))))
#define CONCAT22(a,b) ((unsigned int)(((unsigned short)(a)) << 16 | ((unsigned short)(b))))
#define SCARRY1(a,b) ((((signed char)(a)) < 0) == (((signed char)(b)) < 0) && (((signed char)(a)) + ((signed char)(b)) < 0) != (((signed char)(a)) < 0))
#define SCARRY2(a,b) ((((signed short)(a)) < 0) == (((signed short)(b)) < 0) && (((signed short)(a)) + ((signed short)(b)) < 0) != (((signed short)(a)) < 0))
#define SBORROW2(a,b) ((((signed short)(a)) < 0) != (((signed short)(b)) < 0) && (((signed short)(a)) - ((signed short)(b)) < 0) != (((signed short)(a)) < 0))
#define CARRY1(a,b) ((unsigned int)(a) + (unsigned int)(b) > 0xFF)
#define CARRY2(a,b) ((unsigned int)(a) + (unsigned int)(b) > 0xFFFF)

/* String reference stub - all string references will be resolved to actual strings */
#define s_Empty ""

/* File I/O stubs */
typedef struct {
    int handle;
} FILE_HANDLE;

/* Stack variable stubs */
#define stack0x0002 0

/* Thunk function stubs */
#define thunk_FUN_1000_2ab7 FUN_1000_2ab7

/* Additional type stubs */
typedef int undefined;

#endif /* BADKING_COMPAT_H */
