#ifndef BADKING_COMPAT_H
#define BADKING_COMPAT_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <stdarg.h>

/* Ghidra auto-generated types */
typedef unsigned char undefined1;
typedef unsigned short undefined2;
typedef unsigned int undefined4;
typedef unsigned char byte;
typedef unsigned short word;
typedef unsigned int dword;
typedef int bool;
#define true 1
#define false 0

/* Remove 16-bit calling conventions */
#define __cdecl16far
#define __cdecl16near
#define __cdecl16

/* Stub out Windows 3.x API calls */
#define INITTASK() 1
#define INITAPP(...) 1
#define WAITEVENT(...)
#define LOCKSEGMENT(...)
#define UNLOCKSEGMENT(...)
#define GETWINFLAGS(...) 0
#define LOCALALLOC(...) NULL
#define LOCALFREE(...)
#define LOCALREALLOC(...) NULL
#define BEGINPAINT(...) NULL
#define ENDPAINT(...)
#define CREATECARET(...)
#define DESTROYCARET()
#define CREATEWINDOW(...) NULL
#define DEFWINDOWPROC(...) 0
#define DESTROYWINDOW(...) 0
#define DISPATCHMESSAGE(...) 0
#define ENABLEMENUITEM(...)
#define GETDC(...) NULL
#define GETDESKTOPWINDOW() NULL
#define GETKEYSTATE(...) 0
#define GETMESSAGE(...) 0
#define GETMODULEFILENAME(...) 0
#define GETSTOCKOBJECT(...) NULL
#define GETSYSTEMMENU(...) NULL
#define GETSYSTEMMETRICS(...) 0
#define GETTEXTMETRICS(...) 0
#define INVALIDATERECT(...)
#define LOADCURSOR(...) NULL
#define LOADICON(...) NULL
#define LOADLIBRARY(...) NULL
#define MESSAGEBEEP(...)
#define MESSAGEBOX(...) 0
#define PEEKMESSAGE(...) 0
#define POSTQUITMESSAGE(...)
#define REGISTERCLASS(...) 0
#define RELEASEDC(...)
#define SCROLLWINDOW(...)
#define SELECTOBJECT(...) NULL
#define SETCARETPOS(...)
#define SETSCROLLPOS(...) 0
#define SETSCROLLRANGE(...)
#define SETWINDOWTEXT(...)
#define SHOWCARET(...)
#define SHOWWINDOW(...) 0
#define TRANSLATEMESSAGE(...) 0
#define UPDATEWINDOW(...)
#define TEXTOUT(...)
#define OEMTOANSI(...)
#define _WSPRINTF sprintf

/* Console I/O stubs */
#define _getch getchar
#define _getche getchar
#define _kbhit() 1
#define _putch putchar

/* Window/GUI stubs */
#define __InitEasyWin()
#define __DoneEasyWin()
#define __ExitEasyWin()
#define __CreateEasyWin() NULL
#define __errorBox(x,y)
#define __errorExitBox(x,y)

/* Windows types */
typedef void* HWND;
typedef void* HDC;
typedef void* HINSTANCE;
typedef void* HMODULE;
typedef void* HMENU;
typedef void* HICON;
typedef void* HCURSOR;
typedef void* HBRUSH;
typedef void* HFONT;
typedef void* HBITMAP;
typedef unsigned int UINT;
typedef unsigned long DWORD;
typedef long LONG;
typedef int BOOL;
typedef char* LPSTR;
typedef const char* LPCSTR;
typedef void* LPVOID;
typedef void* FARPROC;

/* MSG structure stub */
typedef struct {
    HWND hwnd;
    UINT message;
    int wParam;
    long lParam;
    DWORD time;
} MSG;

/* PAINTSTRUCT stub */
typedef struct {
    HDC hdc;
    int fErase;
} PAINTSTRUCT;

/* RECT stub */
typedef struct {
    int left;
    int top;
    int right;
    int bottom;
} RECT;

/* TEXTMETRIC stub */
typedef struct {
    int tmHeight;
    int tmAscent;
    int tmDescent;
    int tmInternalLeading;
    int tmExternalLeading;
    int tmAveCharWidth;
    int tmMaxCharWidth;
    int tmWeight;
    int tmOverhang;
    int tmDigitizedAspectX;
    int tmDigitizedAspectY;
    char tmFirstChar;
    char tmLastChar;
    char tmDefaultChar;
    char tmBreakChar;
    char tmItalic;
    char tmUnderlined;
    char tmStruckOut;
    char tmPitchAndFamily;
    char tmCharSet;
} TEXTMETRIC;

/* WNDCLASS stub */
typedef struct {
    UINT style;
    void* lpfnWndProc;
    int cbClsExtra;
    int cbWndExtra;
    HINSTANCE hInstance;
    HICON hIcon;
    HCURSOR hCursor;
    HBRUSH hbrBackground;
    LPCSTR lpszMenuName;
    LPCSTR lpszClassName;
} WNDCLASS;

/* Point stub */
typedef struct {
    int x;
    int y;
} POINT;

/* GetProcAddress stub */
#define GetProcAddress(x,y) NULL

/* MAKEPOINT stub */
#define MAKEPOINT(x) ((POINT){0,0})

/* LOWORD/HIWORD stubs */
#define LOWORD(x) ((unsigned short)(x))
#define HIWORD(x) ((unsigned short)(((unsigned int)(x)) >> 16))

/* VK_ key constants */
#define VK_RETURN 0x0D
#define VK_ESCAPE 0x1B
#define VK_SPACE 0x20

/* Message constants */
#define WM_CREATE 0x0001
#define WM_PAINT 0x000F
#define WM_DESTROY 0x0002
#define WM_KEYDOWN 0x0100
#define WM_CHAR 0x0102
#define WM_LBUTTONDOWN 0x0201
#define WM_COMMAND 0x0111
#define WM_CLOSE 0x0010

/* Window style constants */
#define WS_OVERLAPPEDWINDOW 0x00CF0000
#define CW_USEDEFAULT 0x80000000

/* swi stub - just return 0 */
#define swi(x) 0

/* code type stub */
typedef int (*code)();

/* Ghidra helper macros - these are auto-generated by Ghidra */
#define CONCAT11(a,b) ((unsigned short)(((unsigned char)(a)) << 8 | ((unsigned char)(b))))
#define CONCAT22(a,b) ((unsigned int)(((unsigned short)(a)) << 16 | ((unsigned short)(b))))
#define SCARRY1(a,b) ((((signed char)(a)) < 0) == (((signed char)(b)) < 0) && (((signed char)(a)) + ((signed char)(b)) < 0) != (((signed char)(a)) < 0))
#define SCARRY2(a,b) ((((signed short)(a)) < 0) == (((signed short)(b)) < 0) && (((signed short)(a)) + ((signed short)(b)) < 0) != (((signed short)(a)) < 0))
#define SBORROW2(a,b) ((((signed short)(a)) < 0) != (((signed short)(b)) < 0) && (((signed short)(a)) - ((signed short)(b)) < 0) != (((signed short)(a)) < 0))
#define CARRY1(a,b) ((unsigned int)(a) + (unsigned int)(b) > 0xFF)
#define CARRY2(a,b) ((unsigned int)(a) + (unsigned int)(b) > 0xFFFF)

/* String reference stub */
/* s_Empty removed - conflicts with variable declarations */

/* File I/O stubs */
typedef struct {
    int handle;
} FILE_HANDLE;

/* Stack variable stubs */
#define stack0x0002 0

/* Thunk function stubs */
#define thunk_FUN_1000_2ab7 FUN_1000_2ab7

/* Additional type stubs */
typedef int undefined;
typedef unsigned char unkbyte10[10];
typedef long double longdouble;

#endif /* BADKING_COMPAT_H */
