import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import java.io.FileWriter;
import java.io.PrintWriter;

public class ExportDecompiled extends GhidraScript {

    @Override
    public void run() throws Exception {
        String outputPath = askString("Output path", "Enter output file path:", "/home/thomas/code/badking/decompiled.c");
        PrintWriter writer = new PrintWriter(new FileWriter(outputPath));

        writer.println("// Decompiled from BADKING.EXE");
        writer.println("// Compiled with Borland C++ (1991)");
        writer.println("// Auto-generated by Ghidra decompiler");
        writer.println();

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        FunctionIterator funcs = currentProgram.getFunctionManager().getFunctions(true);
        int count = 0;

        while (funcs.hasNext()) {
            Function func = funcs.next();
            DecompileResults results = decomp.decompileFunction(func, 30, monitor);

            if (results.decompileCompleted()) {
                String cCode = results.getDecompiledFunction().getC();
                if (cCode != null && !cCode.trim().isEmpty()) {
                    writer.println(cCode);
                    writer.println();
                    count++;
                }
            }
        }

        decomp.dispose();
        writer.close();
        println("Exported " + count + " functions to " + outputPath);
    }
}
